# Generated by Django 2.2.6 on 2019-11-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191111_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_search',
            field=models.TextField(default='', max_length=20),
        ),
    ]
